[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "5d74510027896ffb0c8fae2b03ae2abdd4d50a55fab107a4f4892202305dd927"
client_id = "734414180053-tbe9ec9qgj3jb4sbjfpdv9g4o32i50i3.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"